learning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_marathon.urls', namespace='learning_marathon'))
]

learning_marathon/urls.py
from django.urls import path
from . import views

app_name = 'learning_marathon'

urlpatterns = [
    path('', views.index, name='index'),
    path('statistics', views.statistics, name='statistics'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register')
]

learning_marathon/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now

# Create your models here.

class User(AbstractUser):
    first_name = models.CharField(max_length=20)
    now_learning = models.BooleanField(default=False)
    theory = models.BooleanField(default=False)

class LearningSession(models.Model):
    sessionId = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    user = models.ForeignKey("User", on_delete=models.CASCADE, related_name='progress')
    start_date = models.DateTimeField(default=now)
    end_date = models.DateTimeField(default=now)
    theory = models.BooleanField(default=True)

    def duration(self):
        return self.end_date - self.start_date

    def __str__(self):
        return f'{self.user} - learning session'

learning_marathon/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.template.defaulttags import register
from . import make_statistics
import datetime


@register.filter
def get_range(value):
    return range(value)

from .models import User, LearningSession

### Views

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'learning_marathon/login.html')
    if request.method == 'POST':

        if request.user.now_learning:
            current_session = LearningSession.objects.filter(user=request.user).last()
            current_session.end_date = datetime.datetime.now()
            current_session.save()
            request.user.now_learning = False
            request.user.theory = False
            request.user.save()
        else:
            if 'theory' in request.POST:
                current_session = LearningSession.objects.create(user = request.user, theory = True)
                request.user.theory = True
            else:
                current_session = LearningSession.objects.create(user = request.user, theory = False)
            current_session.save()
            request.user.now_learning = True
            request.user.save()
            return HttpResponseRedirect(reverse('learning_marathon:index'))

    return render(request, 'learning_marathon/index.html')

@login_required
def statistics(request):
    data = make_statistics.get_data(request.user)[:-1]
    summary = make_statistics.get_data(request.user)[-1]

    return render(request, 'learning_marathon/statistics.html', {'data':data,
                                                                'summary':summary})

def login_view(request):
    if request.method == "POST":

        username = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('learning_marathon:index'))
        else:
            return render (request,
                        'learning_marathon/login.html',
                        {'error_message': f'Invalid credentials :-('}
                    )

    return render(request, 'learning_marathon/login.html')

def register(request):
    if request.method == 'POST':
        first_name = request.POST['first-name']
        username = request.POST['email']
        password = request.POST['password']
        confirmation = request.POST['confirmation']

        if password != confirmation:
            return render (request,
                        'learning_marathon/register.html',
                        {'error_message': 'Password must match!  :-('}
                    )

        new_user = User.objects.create_user(first_name = first_name, username = username, password = password)
        new_user.save()
        login(request, new_user)
        return render (request,
                        'learning_marathon/index.html',
                        {'success_message': 'Congratulations! Registration successful :-)'}
                    )

    return render(request, 'learning_marathon/register.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_marathon:login'))

learning_marathon/templates/learning_marathon/index.html
{% extends 'learning_marathon/layout.html' %}
{% load static %}
{% block body %}

<div class='row'>
    <div class='col-lg-6 justify-content-center text-center'>
        <h1>Learn theory</h1>
        {% if user.theory %}
            <h3><i class="fas fa-thumbs-up" style='color:green'></i> You are learning now, keep going! :-)</h3>
        {% else %}
            <h3><i class="far fa-frown" style='color:rgb(255, 60, 53)'></i> You're not learning now - let's learn!</h3>
        {% endif %}
        <form action="{% url 'learning_marathon:index' %}" method="POST">
            {% csrf_token %}
        {% if user.now_learning and user.theory %}
        <button type='submit' value='' name='theory' style='background-color: rgba(255, 255, 255, 0);border-color: rgba(255, 255, 255, 0);'>
            <img id='status-learning'
                style="max-width: 100%;width:550px"
                src="{% static 'learning_marathon/progress.png' %}"
                />
        </button>
        {% elif user.now_learning and not user.theory %}
        <img id='status-learning-other'
                style="max-width: 100%;width:550px"
                src="{% static 'learning_marathon/stop.png' %}"
                />
        {% else %}
        <button type='submit' value='' name='theory' style='background-color: rgba(255, 255, 255, 0);border-color: rgba(255, 255, 255, 0);'>
        <img id='status'
            style="max-width: 100%;width:550px"
            src="{% static 'learning_marathon/start.png' %}"
            />
        </button>
        {% endif %}
        </form>
    </div>
    <div class='col-lg-6 justify-content-center text-center'>
    <h1>Enough theory - time for practice!</h1>
    {% if user.now_learning and not user.theory %}
    <h3><i class="fas fa-thumbs-up" style='color:green'></i> You are learning now, keep going! :-)</h3>
    {% else %}
        <h3><i class="far fa-frown" style='color:rgb(255, 60, 53)'></i> You're not learning now - let's learn!</h3>
    {% endif %}
        <form action="{% url 'learning_marathon:index' %}" method="POST">
            {% csrf_token %}
        {% if user.now_learning and not user.theory %}
        <button type='submit' value='' name='practice' style='background-color: rgba(255, 255, 255, 0);border-color: rgba(255, 255, 255, 0);'>
            <img id='status-learning'
                style="max-width: 100%;width:550px"
                src="{% static 'learning_marathon/progress.png' %}"
                />
        </button>
        {% elif user.now_learning and user.theory %}
        <img id='status-learning-other'
            style="max-width: 100%;width:550px"
            src="{% static 'learning_marathon/stop.png' %}"
            />
        {% else %}
        <button type='submit' value='' name='practice' style='background-color: rgba(255, 255, 255, 0);border-color: rgba(255, 255, 255, 0);'>
            <img id='status'
                style="max-width: 100%;width:550px"
                src="{% static 'learning_marathon/start.png' %}"
                />
        </button>
        {% endif %}
        </form>
    </div>
</div>




{% endblock %}

learning_marathon/templates/learning_marathon/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    {% load static %}
    <link rel='stylesheet' href="{% static 'learning_marathon/style.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>

    <script src="jquery-3.5.1.min.js"></script>

    {% if title %}
    <title>Learning Tracker - {{ title }}</title>
    {% else %}
    <title>Learning Tracker</title>
    {% endif %}

    <style>
        body {
            background-image: linear-gradient(to top, #f3dfdf 0%, white 100%);
            min-height: 100vh;
            height: 100%;
            font-family: 'Montserrat';
        }
        #form-login {
            color: whitesmoke;
            border-radius: 10px;
        }
        #name {
            font-size: 20px;
        }

        @media only screen and (max-width: 800px){
            #name {
                font-size: 20px;
            }
    </style>

</head>
<body>
    <nav class='navbar navbar-expand-md navbar-dark bg-danger'>
        <a class="navbar-brand mr-5" href="{% url 'learning_marathon:index' %}">Learning Tracker</a>
        <button class="ml-auto navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            {% if user.is_authenticated %}
            <ul class='navbar-nav mr-auto'>
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'learning_marathon:index' %}">Learning pannel</a>
                </li>
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'learning_marathon:statistics' %}">Statistics</a>
                </li>
            </ul>
            <ul class='navbar-nav ml-auto'>
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'learning_marathon:logout' %}">Log out</a>
                </li>
            </ul>
            {% else %}
            <ul class='navbar-nav ml-auto'>
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'learning_marathon:login' %}">Log in</a>
                </li>
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'learning_marathon:register' %}">Register</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>
    {% if user.is_authenticated %}
    <div class="alert alert-dark w-100 text-center">
        Logged in as {{user.first_name}}
    </div>
    {% endif %}

    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
    {% elif success_message %}
        <div class="alert alert-success">{{ success_message }}</div>
    {% elif error_message %}
    <div class="alert alert-danger">{{ error_message }}</div>
    {% endif %}


    {% block body %}
    {% endblock %}

</body>
</html>

learning_marathon/templates/learning_marathon/login.html
{% extends 'learning_marathon/layout.html' %}
{% load static %}

{% block body %}

<div class='row justify-content-center'>
    <div class='col-md-6 justify-content-center text-center'>
        <img src="{% static 'learning_marathon/logo_transparent.png' %}" style="max-width: 100%;"/>
    </div>

    <div id='form-login' class='align-self-center bg-dark p-4 m-5 col-md-5 text-center'>
        <h1 class='mb-5'>Login</h1>
        <form action="{% url 'learning_marathon:login' %}" method="POST">
            {% csrf_token %}
            <div class='form-group'>
                <input type='text' class='form-control form-control-lg' placeholder="Email" name='email' /><br />
                <input type=password class='form-control form-control-lg' placeholder="Password" name='password' /><br />
                <input type="submit" class='btn btn-danger btn-lg mt-3' value='Sign in'/>
            </div>
        </form>
        <p>Need an Account? <a href="{% url 'learning_marathon:register' %}">Get started now!</a></p>
    </div>
</div>

{% endblock %}

learning_marathon/templates/learning_marathon/register.html
{% extends 'learning_marathon/layout.html' %}
{% load static %}
{% block body %}
<div class='row justify-content-center '>
    <div class='col-md-6 justify-content-center text-center'>
        <img src="{% static 'learning_marathon/logo_transparent.png' %}" style="max-width: 100%;"/>
    </div>

    <div id='form-login' class='align-self-center bg-dark p-4 m-5 col-md-5 justify-content-center text-center'>
        <h1 class='mb-5'>Register</h1>
        <form action="{% url 'learning_marathon:register' %}" method='POST'>
            {% csrf_token %}
            <div class='form-group'>
                <input type='text' class='form-control form-control-lg' placeholder="First name" name='first-name'/><br />
                <input type='text' class='form-control form-control-lg' placeholder="Email" name='email'/><br />
                <input type=password class='form-control form-control-lg' placeholder="Password" name='password'/><br />
                <input type=password class='form-control form-control-lg' placeholder="Confirm password" name='confirmation'/><br />
                <input type="submit" class='btn btn-danger btn-lg mt-3' />
            </div>
        </form>
        <p>Already have an Account? <a href="{% url 'learning_marathon:login' %}">Log in</a></p>
    </div>
    <div class='col-lg-6 justify-content-center text-center'>
        LOGO
    </div>
</div>

{% endblock %}

learning_marathon/templates/learning_marathon/statistics.html
{% extends 'learning_marathon/layout.html' %}
{% load static %}
{% block body %}
<div class='p-md-5 m-1'>
    <div class='row align-content-center m-3 bg-dark' style='color:whitesmoke;border-radius:10px;min-height:70px'>
        <div class='col-lg-2'>
        </div>
        <div class='col-lg-5'>
            <p id='name'>Theory</p>
        </div>
        <div class='col-lg-5 text-right'>
            <p id='name'>Practice</p>
        </div>
    </div>


    {% for day in data %}
    <div class='row align-content-center m-3' style='min-height:50px'>
        <div class='col-lg-2'>
            {{ day.day }}
        </div>
        <div class='col-lg-1'>
            {{ day.theory }}
        </div>
        <div class='col-lg-4'>
            {% if day.rewards %}
            {% for reward in day.rewards|get_range %}
            <i style='height: 20px;font-size: 20px;' class="fas fa-star"></i>
            {% endfor %}
            {% endif %}
        </div>
        <div class='col-lg-4 text-right'>
            {% if day.rewards_practice %}
            {% for reward in day.rewards_practice|get_range %}
            <i style='height: 20px;font-size: 20px;' class="far fa-star"></i>
            {% endfor %}
            {% endif %}
        </div>
        <div class='col-lg-1 text-right'>
            {{ day.practice }}
        </div>

    </div>

    <hr />
    {% endfor %}

    <div class='row align-content-center m-3 bg-dark' style='color:whitesmoke;border-radius:10px;min-height:70px'>
        <div class='col-lg-2'>
            Summary: <i style='height: 20px;font-size: 30px;' class="fas fa-star"></i>
        </div>
        <div class='col-lg-5'>
            <p id='name'>{{ summary.theory_summary }}</p>
        </div>
        <div class='col-lg-5 text-right'>
            <p id='name'>{{ summary.practice_summary }}</p>
        </div>
    </div>
</div>

{% endblock %}